export const restaurantsData = [
  {
    name: "The Duke",
    address: "London, UK",
    menus: [
      {
        name: "Dinner Menu",
        menuItems: [
          {
            name: "Sourdough, whipped seaweedbutter",
            course: "Starters",
            price: "4.50",
            description:
              "House baked sourdoug bread, with whipped homemade butter",
            gluten: "integral",
            dairy: "removable",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "integral",
            molluscs: "integral",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "notIncluded",
            diet: "vegetarian",
          },
          {
            name: "Marinated Olives",
            course: "Starters",
            price: "4",
            description: "",
            gluten: "notIncluded",
            dairy: "notIncluded",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notInlcuded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "integral",
            fish: "notIncluded",
            diet: "vegan",
          },
          {
            name: "Roasted peanuts",
            course: "Starters",
            price: "3",
            description: "",
            gluten: "notIncluded",
            dairy: "notIncluded",
            nuts: "integral",
            peanuts: "integral",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notInlcuded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "notIncluded",
            diet: "vegan",
          },
          {
            name: "Croquettes, leaves",
            course: "Starters",
            price: "3",
            description: "Mushroom filled croquettes",
            gluten: "integral",
            dairy: "notIncluded",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "integral",
            sulphites: "notIncluded",
            eggs: "notInlcuded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "notIncluded",
            diet: "vegan",
          },
          {
            name: "Burrata, black olive & honey",
            course: "Starters",
            price: "3",
            description: "",
            gluten: "notIncluded",
            dairy: "integral",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notInlcuded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "notIncluded",
            diet: "vegetarian",
          },
          {
            name: "Beetroot salad, sauerkraut & hazelnut",
            course: "Starters",
            price: "8.5",
            description: "",
            gluten: "notIncluded",
            dairy: "notIncluded",
            nuts: "integral",
            peanuts: "integral",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notInlcuded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "notIncluded",
            diet: "vegan",
          },
          {
            name: "Brown crab aioli, toast",
            course: "Starters",
            price: "9",
            description: "",
            gluten: "integral",
            dairy: "notIncluded",
            nuts: "integral",
            peanuts: "integral",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "integral",
            lupin: "notIncluded",
            crustacean: "integral",
            molluscs: "notIncluded",
            mustard: "integral",
            celery: "notIncluded",
            fish: "notIncluded",
            diet: "pescatarian",
          },
          {
            name: "Coppa, fig, almond",
            course: "Starters",
            price: "9",
            description: "",
            gluten: "notIncluded",
            dairy: "notIncluded",
            nuts: "integral",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "notIncluded",
            diet: "noDiet",
          },
          {
            name: "Corgette & Taleggio gratin, truffle",
            course: "Starters",
            price: "10",
            description: "",
            gluten: "notIncluded",
            dairy: "integral",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "notIncluded",
            diet: "vegetarian",
          },
          {
            name: "Parsnip & red lentil soup",
            course: "Starters",
            price: "7",
            description: "",
            gluten: "notIncluded",
            dairy: "notIncluded",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "notIncluded",
            diet: "vegan",
          },
          {
            name: "Day Boat fish, shellfish sauce",
            course: "Mains",
            price: "16",
            description: "",
            gluten: "notIncluded",
            dairy: "notIncluded",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "removable",
            molluscs: "removable",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "integral",
            diet: "pescatarian",
          },
          {
            name: "Squash, spelt, Champagne lentils",
            course: "Mains",
            price: "16",
            description: "",
            gluten: "removable",
            dairy: "notIncluded",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "included",
            fish: "notIncluded",
            diet: "vegetarian",
          },
          {
            name: "Borlotti beans, salsa Puttanesca",
            course: "Mains",
            price: "16",
            description: "",
            gluten: "removable",
            dairy: "notIncluded",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "integral",
            fish: "notIncluded",
            diet: "vegetarian",
          },
          {
            name: "Pork, cep cream, cauliflower & leeks",
            course: "Mains",
            price: "20",
            description: "",
            gluten: "notIncluded",
            dairy: "removable",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "removable",
            fish: "notIncluded",
            diet: "noDiet",
          },
          {
            name: "Saute potatoes, Romesco Sauce",
            course: "Sides",
            price: "4",
            description: "",
            gluten: "notIncluded",
            dairy: "notInluded",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "notIncluded",
            diet: "vegan",
          },
          {
            name: "Seasonal greens",
            course: "Sides",
            price: "4",
            description: "",
            gluten: "notIncluded",
            dairy: "notInluded",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "notIncluded",
            diet: "vegan",
          },
          {
            name: "Leaf salad, mustard dressing",
            course: "Sides",
            price: "4",
            description: "",
            gluten: "notIncluded",
            dairy: "notInluded",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "removable",
            celery: "notIncluded",
            fish: "notIncluded",
            diet: "vegan",
          },
          {
            name: "Montezuma chocolate brownie",
            course: "Dessert",
            price: "7",
            description: "",
            gluten: "integral",
            dairy: "integral",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "integral",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "notIncluded",
            diet: "vegetarian",
          },
          {
            name: "Seasonal fruit crumble",
            course: "Dessert",
            price: "7",
            description: "",
            gluten: "integral",
            dairy: "notInluded",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "removable",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "notIncluded",
            diet: "vegan",
          },
          {
            name: "Poached pear, Jersey cream",
            course: "Dessert",
            price: "7",
            description: "",
            gluten: "notIncluded",
            dairy: "integral",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "notIncluded",
            diet: "vegetarian",
          },
        ],
      },
      {
        name: "Christmas Menu",
        menuItems: [
          {
            name: "Roast Turkey",
            course: "Mains",
            price: "18.99",
            description: "",
            gluten: "integral",
            dairy: "integral",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "integral",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "integral",
            fish: "notIncluded",
            diet: "noDiet",
          },
        ],
      },
    ],
  },
  {
    name: "Mc Donalds",
    address: "London, UK",
    menus: [
      {
        name: "Super Saver Menu",
        menuItems: [
          {
            name: "Cheeseburger",
            course: "Mains",
            price: "0.99",
            description: "",
            gluten: "integral",
            dairy: "removable",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "integral",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "removable",
            celery: "notIncluded",
            fish: "notIncluded",
            diet: "noDiet",
          },
          {
            name: "Four Piece Nuggets",
            course: "Starter",
            price: "0.99",
            description: "",
            gluten: "integral",
            dairy: "integral",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "integral",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "notIncluded",
            diet: "noDiet",
          },
        ],
      },
      {
        name: "Main Menu",
        menuItems: [
          {
            name: "Big Mac",
            course: "Mains",
            price: "3.99",
            description: "",
            gluten: "integral",
            dairy: "removable",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "integral",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "removable",
            celery: "notIncluded",
            fish: "notIncluded",
            diet: "noDiet",
          },
          {
            name: "Mc Flurry",
            course: "Dessert",
            price: "1.5",
            description: "",
            gluten: "notIncluded",
            dairy: "integral",
            nuts: "removable",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "notIncluded",
            diet: "noDiet",
          },
        ],
      },
    ],
  },
];
