export const restaurantsData = [
  {
    name: "The Duke",
    address: "London, UK",
    menus: [
      {
        name: "Dinner Menu",
        menuItems: [
          {
            name: "Sourdough, whipped seaweedbutter",
            course: "Starters",
            price: "4.50",
            description:
              "House baked sourdoug bread, with whipped homemade butter",
            gluten: "integral",
            dairy: "removable",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "integral",
            molluscs: "integral",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "notIncluded",
            vegan: "removable",
            veg: "notIncluded",
            pescatarian: "notIncluded",
          },
          {
            name: "Marinated Olives",
            course: "Starters",
            price: "4",
            description: "",
            gluten: "notIncluded",
            dairy: "notIncluded",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notInlcuded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "integral",
            fish: "notIncluded",
            vegan: "notIncluded",
            veg: "notIncluded",
            pescatarian: "notIncluded",
          },
          {
            name: "Roasted peanuts",
            course: "Starters",
            price: "3",
            description: "",
            gluten: "notIncluded",
            dairy: "notIncluded",
            nuts: "integral",
            peanuts: "integral",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "notIncluded",
            vegan: "notIncluded",
            veg: "notIncluded",
            pescatarian: "notIncluded",
          },
          {
            name: "Croquettes, leaves",
            course: "Starters",
            price: "3",
            description: "Mushroom filled croquettes",
            gluten: "integral",
            dairy: "notIncluded",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "integral",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "notIncluded",
            vegan: "notIncluded",
            veg: "notIncluded",
            pescatarian: "notIncluded",
          },
          {
            name: "Burrata",
            course: "Starters",
            price: "3",
            description:
              "A soft creamy Italian favourite, with black olive & honey",
            gluten: "notIncluded",
            dairy: "integral",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "notIncluded",
            vegan: "integral",
            veg: "notIncluded",
            pescatarian: "notIncluded",
          },
          {
            name: "Beetroot salad",
            course: "Starters",
            price: "8.5",
            description: "Rich and colorful beets with sauerkraut & hazelnut",
            gluten: "notIncluded",
            dairy: "notIncluded",
            nuts: "integral",
            peanuts: "integral",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "notIncluded",
            vegan: "notIncluded",
            veg: "notIncluded",
            pescatarian: "notIncluded",
          },
          {
            name: "Brown crab aioli, toast",
            course: "Starters",
            price: "9",
            description: "Fresh locally caught crab on housebaked sourdough",
            gluten: "integral",
            dairy: "notIncluded",
            nuts: "integral",
            peanuts: "integral",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "integral",
            lupin: "notIncluded",
            crustacean: "integral",
            molluscs: "notIncluded",
            mustard: "integral",
            celery: "notIncluded",
            fish: "notIncluded",
            diet: "pescatarian",
            vegan: "integral",
            veg: "integral",
            pescatarian: "notIncluded",
          },
          {
            name: "Coppa, fig, almond",
            course: "Starters",
            price: "9",
            description:
              "Dry cured Capocollo complemented with fresh figs and toasted almonds",
            gluten: "notIncluded",
            dairy: "notIncluded",
            nuts: "integral",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "notIncluded",
            diet: "noDiet",
            vegan: "integral",
            veg: "integral",
            pescatarian: "integral",
          },
          {
            name: "Corgette & Taleggio gratin, truffle",
            course: "Starters",
            price: "10",
            description:
              "Soft and mild aged taleggio cheese baked to perfection and topped with seasonal truffle",
            gluten: "notIncluded",
            dairy: "integral",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "notIncluded",
            vegan: "integral",
            veg: "notIncluded",
            pescatarian: "notIncluded",
          },
          {
            name: "Parsnip & red lentil soup",
            course: "Starters",
            price: "7",
            description:
              "A warm and spicy vegetable soup, perfect for any occasion",
            gluten: "notIncluded",
            dairy: "notIncluded",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "notIncluded",
            diet: "vegan",
            vegan: "notIncluded",
            veg: "notIncluded",
            pescatarian: "notIncluded",
          },
          {
            name: "Day Boat fish, shellfish sauce",
            course: "Mains",
            price: "16",
            description:
              "Line caught fish, served with vegetables and a white wine shellfish sauce",
            gluten: "notIncluded",
            dairy: "notIncluded",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "removable",
            molluscs: "removable",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "integral",
            vegan: "integral",
            veg: "integral",
            pescatarian: "notIncluded",
          },
          {
            name: "Squash, spelt, Champagne lentils",
            course: "Mains",
            price: "16",
            description: "Yellow Squash on a bed of lentils and spelt",
            gluten: "removable",
            dairy: "notIncluded",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "integral",
            fish: "notIncluded",
            vegan: "notIncluded",
            veg: "notIncluded",
            pescatarian: "notIncluded",
          },
          {
            name: "Borlotti beans, salsa Puttanesca",
            course: "Mains",
            price: "16",
            description:
              "Slow cooked beans served with a traditional italian Puttanesca sause",
            gluten: "removable",
            dairy: "notIncluded",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "integral",
            fish: "notIncluded",
            vegan: "notIncluded",
            veg: "notIncluded",
            pescatarian: "notIncluded",
          },
          {
            name: "Pork, cep cream, cauliflower & leeks",
            course: "Mains",
            price: "20",
            description:
              "Local buchered pork shoulder complimented with roasted cauliflowers and leeks",
            gluten: "notIncluded",
            dairy: "removable",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "removable",
            fish: "notIncluded",
            vegan: "integral",
            veg: "integral",
            pescatarian: "integral",
          },
          {
            name: "Saute potatoes, Romesco Sauce",
            course: "Sides",
            price: "4",
            description: "Twice cooked potatoes in a spicy red pepper salsa",
            gluten: "notIncluded",
            dairy: "notInluded",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "notIncluded",
            vegan: "notIncluded",
            veg: "notIncluded",
            pescatarian: "notIncluded",
          },
          {
            name: "Seasonal greens",
            course: "Sides",
            price: "4",
            description: "Local seasonal greens sauted with garlic and herbs",
            gluten: "notIncluded",
            dairy: "notInluded",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "notIncluded",
            vegan: "notIncluded",
            veg: "notIncluded",
            pescatarian: "notIncluded",
          },
          {
            name: "Leaf salad",
            course: "Sides",
            price: "4",
            description: "Mixed leaf salad with a house made mustard dressing",
            gluten: "notIncluded",
            dairy: "notInluded",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "removable",
            celery: "notIncluded",
            fish: "notIncluded",
            vegan: "notIncluded",
            veg: "notIncluded",
            pescatarian: "notIncluded",
          },
          {
            name: "Montezuma chocolate brownie",
            course: "Dessert",
            price: "7",
            description:
              "A rich, warm and nutty chocolate treat served with house made vanilla icecream",
            gluten: "integral",
            dairy: "integral",
            nuts: "integral",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "integral",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "notIncluded",
            vegan: "integral",
            veg: "notIncluded",
            pescatarian: "notIncluded",
          },
          {
            name: "Seasonal fruit crumble",
            course: "Dessert",
            price: "7",
            description:
              "Homebaked apple crumble served with a rich and creamy custard",
            gluten: "integral",
            dairy: "removable",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "removable",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "notIncluded",
            vegan: "notIncluded",
            veg: "notIncluded",
            pescatarian: "notIncluded",
          },
          {
            name: "Poached pear",
            course: "Dessert",
            price: "7",
            description:
              "Flash poached and peeled sweet seasonal pear served with Jersey cream",
            gluten: "notIncluded",
            dairy: "integral",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "notIncluded",
            vegan: "notIncluded",
            veg: "notIncluded",
            pescatarian: "notIncluded",
          },
        ],
      },
      {
        name: "Christmas Menu",
        menuItems: [
          {
            name: "Roast Turkey",
            course: "Mains",
            price: "18.99",
            description: "",
            gluten: "integral",
            dairy: "integral",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "integral",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "integral",
            fish: "notIncluded",
            vegan: "integral",
            veg: "integral",
            pescatarian: "integral",
          },
        ],
      },
    ],
  },
  {
    name: "Mc Donalds",
    address: "London, UK",
    menus: [
      {
        name: "Super Saver Menu",
        menuItems: [
          {
            name: "Cheeseburger",
            course: "Mains",
            price: "0.99",
            description: "",
            gluten: "integral",
            dairy: "removable",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "integral",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "removable",
            celery: "notIncluded",
            fish: "notIncluded",
            vegan: "integral",
            veg: "integral",
            pescatarian: "integral",
          },
          {
            name: "Four Piece Nuggets",
            course: "Starter",
            price: "0.99",
            description: "",
            gluten: "integral",
            dairy: "integral",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "integral",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "notIncluded",
            vegan: "integral",
            veg: "integral",
            pescatarian: "integral",
          },
        ],
      },
      {
        name: "Main Menu",
        menuItems: [
          {
            name: "Big Mac",
            course: "Mains",
            price: "3.99",
            description: "",
            gluten: "integral",
            dairy: "removable",
            nuts: "notIncluded",
            peanuts: "notIncluded",
            sesame: "integral",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "removable",
            celery: "notIncluded",
            fish: "notIncluded",
            vegan: "integral",
            veg: "integral",
            pescatarian: "integral",
          },
          {
            name: "Mc Flurry",
            course: "Dessert",
            price: "1.5",
            description: "",
            gluten: "notIncluded",
            dairy: "integral",
            nuts: "removable",
            peanuts: "notIncluded",
            sesame: "notIncluded",
            soya: "notIncluded",
            sulphites: "notIncluded",
            eggs: "notIncluded",
            lupin: "notIncluded",
            crustacean: "notIncluded",
            molluscs: "notIncluded",
            mustard: "notIncluded",
            celery: "notIncluded",
            fish: "notIncluded",
            vegan: "notIncluded",
            veg: "notIncluded",
            pescatarian: "integral",
          },
        ],
      },
    ],
  },
];
